postgresql: 
  image: 10.0.0.5:8086/library/postgres
  environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production
  expose:
    - "5432"
gitlab:
  image: 10.0.0.5:8086/shaomq/gitlab
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "80"
    - "22"
  environment:
    - DB_NAME=gitlabhq_production
    - DB_PASS=password
    - DB_TYPE=postgres
    - DB_USER=gitlab
    - GITLAB_SSH_PORT=10022
    - DB_HOST=$POSTGRESQL_PORT_5432_TCP_ADDR
    - DB_PORT=$POSTGRESQL_PORT_5432_TCP_PORT
    - REDIS_HOST=$REDISIO_PORT_6379_TCP_ADDR
    - REDIS_PORT=$REDISIO_PORT_6379_TCP_PORT
redis:
  image: 10.0.0.5:8086/library/redis
  expose:
    - "6379"
